# Generated by Django 3.2 on 2022-09-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True),
        ),
    ]
