# Generated by Django 3.2 on 2022-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
    ]
